spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/app_my_todo
            database: app_my_todo

    jpa:
        hibernate:
            ddl-auto: update

        show-sql: true